
services:
  app:
    build: .
    container_name: express-app
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - PORT=3000
      - REDIS_PORT=6379

    ports:
      - "3000:3000"